version: '3.8'

services:
  # 1. Servicio de la App Django (tu API)
  web:
    build: .
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn backend_project.wsgi:application --bind 0.0.0.0:8000 --workers 3
      "    
    volumes:
      - .:/app
    ports:
      - "8086:8000"
    env_file:
      - ./.env
    environment:
      - MYSQL_HOST=db
    depends_on:
      db:
        condition: service_healthy

  # 2. Servicio de la Base de Datos MySQL
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env # Carga las variables (SOLO la DB y la ROOT_PASSWORD)
    healthcheck:
      # (¡CAMBIO 1!) Le decimos que el usuario es 'root'
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 3. Servicio de phpMyAdmin (Tu "vista" de la DB)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8087:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      # (¡CAMBIO 2!) Le decimos que el usuario es 'root'
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD} # Lee la clave del .env
    depends_on:
      - db

volumes:
  mysql_data: